/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT8127. Copyright MediaTek Inc. (C) 2013.
 * Fri Oct 09 18:38:33 2015
 * Do Not Modify the File.
 */



#include "pmic_drv.h"



//For PMIC driver use


